#  Custom Tomcat server port
server:
  port: 8088

#  Custom referenced value
welcome:
  message: Hello World, welcome to CodePrac with Shaviya!

#  database connection information
spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    continue-on-error: true
    initialization-mode: always
    initialize: true
    #  Add Crucial DB details for department_API project below

    password: Adm!n_p0stgr3s
    url: jdbc:postgresql://localhost:5432/department_api
    username: postgres
